import {
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogContentText,
  DialogTitle,
  Typography,
} from "@mui/material";
import React from "react";

interface TermsModalProps {
  open: boolean;
  onClose: () => void;
}

const TermsModal = ({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) => {
  return (
    <Dialog
      open={open}
      onClose={onClose}
      scroll="paper"
      aria-labelledby="terms-dialog-title"
      fullWidth
    >
      <DialogTitle id="terms-dialog-title">Terms and Conditions</DialogTitle>
      <DialogContent dividers>
        <Box sx={{ color: "text.secondary" }}>
          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 2 }}
          >
            1. Definitions
          </Typography>
          <Typography variant="body2" paragraph>
            <strong>Platform</strong> – SaaS (Software as a Service) provided by
            the Service Provider.
            <br />
            <strong>Service Provider</strong> – the owner and operator of the
            Platform.
            <br />
            <strong>Administrator (Client)</strong> – a business entity or
            authorized person holding an account with administrative privileges,
            managing the access of other Users.
            <br />
            <strong>End User</strong> – a natural person invited to use the
            Platform by the Administrator.
          </Typography>

          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 3 }}
          >
            2. Platform Access and Registration
          </Typography>
          <Typography variant="body2" paragraph>
            Access to the Platform is restricted. Creating an End User account
            is only possible by receiving a dedicated e-mail invitation
            ("Register here") generated from the Administrator Panel. The
            Administrator is fully responsible for the list of e-mail addresses
            to which invitations are sent, and for assigning appropriate roles
            and permissions (RBAC) within their organization. The registration
            link is single-use and expires 48 hours after being generated by the
            system.
          </Typography>

          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 3 }}
          >
            3. User Rights and Responsibilities
          </Typography>
          <Typography variant="body2" paragraph>
            The User agrees to use the Platform in accordance with its intended
            purpose, applicable law, and good business practices. It is strictly
            prohibited to:
          </Typography>
          <Typography variant="body2" component="ul" sx={{ pl: 3, mb: 2 }}>
            <li>Use the Platform to transmit spam or malicious software.</li>
            <li>Attempt reverse engineering of the Platform's code.</li>
            <li>Share a single User account among multiple natural persons.</li>
          </Typography>
          <Typography variant="body2" paragraph>
            The Service Provider reserves the right to immediately suspend a
            User's account in the event of a breach of these Terms.
          </Typography>

          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 3 }}
          >
            4. Service Availability and Maintenance (SLA)
          </Typography>
          <Typography variant="body2" paragraph>
            The Service Provider makes every effort to ensure uninterrupted
            access to the Platform at a level of 99.9% on a monthly basis (SLA).
            Due to the growing scale of the system and the processing of
            thousands of active sessions, the Service Provider reserves the
            right to conduct regular maintenance windows for the purpose of
            database and server infrastructure optimization. Maintenance windows
            will be scheduled during periods of lowest traffic. Administrators
            will be notified of planned maintenance at least 48 hours in
            advance.
          </Typography>

          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 3 }}
          >
            5. Confidentiality and Data Protection (GDPR)
          </Typography>
          <Typography variant="body2" paragraph>
            The Service Provider processes Users' personal data solely for the
            purpose of providing the services, acting as a Data Processor, based
            on the Data Processing Agreement (DPA) concluded with the
            Administrator. All data entered into the Platform is encrypted (in
            transit and at rest) using industry standards.
          </Typography>

          <Typography
            variant="h6"
            color="text.primary"
            gutterBottom
            sx={{ mt: 3 }}
          >
            6. Final Provisions
          </Typography>
          <Typography variant="body2" paragraph>
            The Service Provider reserves the right to amend these Terms.
            Administrators will be notified of any changes via e-mail 14 days
            before they take effect.
          </Typography>
        </Box>
      </DialogContent>

      <DialogActions sx={{ px: 3, py: 2 }}>
        <Button onClick={onClose} color="primary" variant="contained">
          I understand and close
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default TermsModal;
